// Подборка крупных городов мира для автоподсказок (формат "Город, Страна").
// Не исчерпывающий список — юзер может ввести свой город вручную.
export const WORLD_CITIES = [
  "Amsterdam, Netherlands", "Rotterdam, Netherlands", "The Hague, Netherlands",
  "Utrecht, Netherlands", "Eindhoven, Netherlands", "Groningen, Netherlands",
  "London, United Kingdom", "Manchester, United Kingdom", "Birmingham, United Kingdom",
  "Berlin, Germany", "Munich, Germany", "Hamburg, Germany", "Cologne, Germany", "Frankfurt, Germany",
  "Paris, France", "Lyon, France", "Marseille, France", "Nice, France",
  "Madrid, Spain", "Barcelona, Spain", "Valencia, Spain", "Seville, Spain",
  "Lisbon, Portugal", "Porto, Portugal",
  "Rome, Italy", "Milan, Italy", "Naples, Italy", "Turin, Italy", "Florence, Italy",
  "Vienna, Austria", "Zurich, Switzerland", "Geneva, Switzerland",
  "Brussels, Belgium", "Antwerp, Belgium",
  "Dublin, Ireland", "Copenhagen, Denmark", "Stockholm, Sweden", "Oslo, Norway", "Helsinki, Finland",
  "Warsaw, Poland", "Krakow, Poland", "Prague, Czech Republic", "Budapest, Hungary",
  "Athens, Greece", "Bucharest, Romania", "Sofia, Bulgaria", "Zagreb, Croatia",
  "Kyiv, Ukraine", "Lviv, Ukraine", "Odesa, Ukraine", "Kharkiv, Ukraine",
  "Moscow, Russia", "Saint Petersburg, Russia",
  "Istanbul, Turkey", "Ankara, Turkey", "Izmir, Turkey",
  "Tel Aviv, Israel", "Jerusalem, Israel", "Dubai, UAE", "Abu Dhabi, UAE", "Doha, Qatar", "Riyadh, Saudi Arabia",
  "New York, USA", "Los Angeles, USA", "Chicago, USA", "San Francisco, USA", "Miami, USA",
  "Seattle, USA", "Boston, USA", "Austin, USA", "Las Vegas, USA", "Washington, USA",
  "Toronto, Canada", "Vancouver, Canada", "Montreal, Canada",
  "Mexico City, Mexico", "Guadalajara, Mexico",
  "Sao Paulo, Brazil", "Rio de Janeiro, Brazil", "Buenos Aires, Argentina", "Santiago, Chile",
  "Bogota, Colombia", "Lima, Peru",
  "Cairo, Egypt", "Lagos, Nigeria", "Nairobi, Kenya", "Cape Town, South Africa", "Johannesburg, South Africa",
  "Casablanca, Morocco", "Tunis, Tunisia",
  "Tokyo, Japan", "Osaka, Japan", "Kyoto, Japan",
  "Seoul, South Korea", "Beijing, China", "Shanghai, China", "Hong Kong, China",
  "Bangkok, Thailand", "Singapore, Singapore", "Kuala Lumpur, Malaysia", "Jakarta, Indonesia", "Bali, Indonesia",
  "Manila, Philippines", "Ho Chi Minh City, Vietnam", "Hanoi, Vietnam",
  "Mumbai, India", "Delhi, India", "Bangalore, India",
  "Sydney, Australia", "Melbourne, Australia", "Brisbane, Australia", "Auckland, New Zealand",
  "Tbilisi, Georgia", "Yerevan, Armenia", "Almaty, Kazakhstan", "Tashkent, Uzbekistan", "Baku, Azerbaijan",
  "Belgrade, Serbia", "Tallinn, Estonia", "Riga, Latvia", "Vilnius, Lithuania", "Reykjavik, Iceland",
];
